### PR TITLE
Checked with latest Steam & OpenVR & Ubuntu14.04 & ROS Indigo (2018/01/23)

### PR DESCRIPTION
**Pull request by ishiguroJSK**
- OpenGL image transport -> OK
- controller button publish -> OK
- controller viblation -> not working
- Vulkan -> not working

We can run with 
`roslaunch vive_ros vive.launch`
(and if you want)
`rosrun usb_cam usb_cam_node usb_cam/image_raw:=image_left`

We can run with 1000Hz when we comment out `#define USE_IMAGE` in vive_node.cpp

### CODE REVIEW

**Comment by lcluz** [comment]
Hi. Sorry for the fact that it took us a very long time to reply to you. The person who did it no longer works with us and we never really used Vive again. I am trying to run your fork in the vulkan-dev-2018 and I have some "errors" to report before i can merge your request:
**1.** the path for the steam vr is no longer in ~/.local/share/Steam, but in ~/.steam/steam;
**2.** If I have #define USE_IMAGE the script compiles but when running it crashes:
[ INFO] [1554389086.236443765]:  [VIVE] World offset: [0.000 , 0.000, 2.000] 0.000
Using vrcompositor capability proxy
Failed to raise ambient cap
Launching /home/jefferino/.steam/steam/steamapps/common/SteamVR/bin/linux64/vrcompositor
Using breakpad crash handler
Setting breakpad minidump AppID = 250820
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
assert_20190404154447_1.dmp[31680]: Uploading dump (out-of-process)
/tmp/dumps/assert_20190404154447_1.dmp
assert_20190404154447_1.dmp[31680]: Finished uploading minidump (out-of-process): success = no
assert_20190404154447_1.dmp[31680]: error: libcurl.so: cannot open shared object file: No such file or directory
assert_20190404154447_1.dmp[31680]: file ''/tmp/dumps/assert_20190404154447_1.dmp'', upload no: ''libcurl.so: cannot open shared object file: No such file or directory''
Using breakpad crash handler
Setting breakpad minidump AppID = 250820
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Cannot mix incompatible Qt library (version 0x50500) with this library (version 0x50501)
crash_20190404154448_1.dmp[31691]: Uploading dump (out-of-process)
/tmp/dumps/crash_20190404154448_1.dmp
crash_20190404154448_1.dmp[31691]: Finished uploading minidump (out-of-process): success = no
crash_20190404154448_1.dmp[31691]: error: libcurl.so: cannot open shared object file: No such file or directory
crash_20190404154448_1.dmp[31691]: file ''/tmp/dumps/crash_20190404154448_1.dmp'', upload no: ''libcurl.so: cannot open shared object file: No such file or directory''
VIVE Info: Shutting down.

Notes:
- I will close your other request, since it seems to be related to this one.
- Your update on the joy is very useful, well done.

**Comment by ishiguroJSK** [comment]
OK. Since steam and steamVR are frequently updated and lose compatibility, I can understand several errors will occurs with this Pull Request.
We now mainly working with ROS Kinetic on Ubuntu16.04, and I've already checked these features with my branch.
By the way, do you still have power to maintain this repository ?
If the image rendering features are merged, the codes will be getting more complex and need more frequent maintenance to catch up with the latest SteamVR update.
(There is still no official repository, and I'm still searching for where to commit latest work...)

> I will close your other request, since it seems to be related to this one.

OK I'll close by myself.

> Your update on the joy is very useful, well done.

Thanks for @iory

**Comment by lcluz** [comment]
Yes, we really want to get back at updating this repo, since we also have interested due to our work.
btw, did you ever use the htc vive with a sync cable?

**Comment by ishiguroJSK** [comment]
> Yes, we really want to get back at updating this repo, since we also have interested due to our work.

OK, I'll re-check on both 14.04 and 16.04, and update my PR.

> btw, did you ever use the htc vive with a sync cable?

"sync cable" means the timing sync cable connected to lighthouse station?
If so, I haven't used that.

**Pull request merged**
